### ISSUE TITLE
Android: Manifest merger failed

### ISSUE THREAD

**Issue by rliljest** [electrode-io/ernnavigation-api-impl-native#26]
I've been trying to build a "hello world" mini-app with `ernnavigation-api-impl-native` as a dependency, but get stuck when trying to build. Here are my steps:

```
ern create-miniapp --language JavaScript -v 0.37.0 --skipNpmCheck --packageManager npm HelloWorldMiniApp
cd HelloWorldMiniApp
ern add "ernnavigation-api-impl-native@1.2.0"
ern run-android
```

This eventually fails with the following error:

```
✖ Building and installing application 3s
✖ An error occurred: Command failed: ./gradlew installDebug
✖ /Users/.../HelloWorldMiniApp/android/app/src/main/AndroidManifest.xml:22:18-91 Error:
✖ 	Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
✖ 	is also present at [androidx.core:core:1.0.1] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
✖ 	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:8:5-22:19 to override.
✖ 
✖ FAILURE: Build failed with an exception.
✖ 
✖ * What went wrong:
✖ Execution failed for task ':app:processDebugManifest'.
✖ > Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
✖   	is also present at [androidx.core:core:1.0.1] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
✖   	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:8:5-22:19 to override.
✖ 
✖ * Try:
✖ Run with --stacktrace option to get the stack trace. Run with --info or --debu
g option to get more log output. Run with --scan to get full insights.
✖ 
✖ * Get more help at https://help.gradle.org
✖ 
✖ BUILD FAILED in 2s
```

My understanding is that androidx requires `react-native@0.60.0` or newer, but the latest electrode-native manifest version is `0.59.10`.

Alternatively, it looks like there should be a new miniapp runner project that we could use with this repository (notes on https://github.com/electrode-io/electrode-native/releases/tag/v0.37.0), but there is no documentation on how to use it. So if I'm off the mark attempting to pull in `ernnavigation-api-impl-native` into the stock miniapp runner and should be using the "new" one instead, then some guidance/documentation on how to use the new runner would be helpful.

Thanks and let me know if more info is needed

**Comment by deepueg** [comment]
@rliljest,  The best way to add `ern-navigation` to your project is to add `ern-navigation` dependency to your mini-app, which has defined a proper transitive dependency with right versions of the `ern-navigation-api` and `ernnavigation-api-impl-native`.  

In your case, please try the following,
1. Upgrade to the latest version of ern using `ern platform use latest`
2. delete the `android` folder from workspace
3. Run `ern run-android` again. 

Please let us know if that doesn't resolve this issue.

**Comment by rliljest** [comment]
Thanks! Using my initial steps but adding `ern-navigation@1.1.2` instead of `ernnavigation-api-impl-native@1.2.0` fixed the build issue and the app appears to be working as expected
