### ISSUE TITLE
iOS: Nav Bar Buttons don't respect "disabled" property

### ISSUE THREAD

**Issue by rliljest** [electrode-io/ernnavigation-api-impl-native#47]
You cannot currently set a disabled nav bar button on iOS even though the API supports it. The button will always be enabled. I think there needs to be an update in `ENNavigationDelegate.swift:getUIBarButtonItem`, adding something like this before the return statement:

`button.isEnabled = !(navigationButton.disabled ?? false)`

**Comment by deepueg** [comment]
@rliljest Thanks for reporting and sorry for the delay. we will take a look at this.
